name: mobx_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  mobx: ^2.0.7+5
  mobx_codegen: ^2.0.7
  provider: ^6.0.3

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true
